# Generated by Django 6.0.7 on 2026-07-13 19:04

import django.core.validators
import django.db.models.deletion
import images.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.ImageField(max_length=500, upload_to=images.models.original_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=50)),
                ('file_size', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(default=images.models.default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('resize', 'Resize'), ('webp', 'Convert to WebP'), ('thumbnail', 'Thumbnail'), ('compress', 'Compress'), ('remove_background', 'Remove background'), ('remove_metadata', 'Remove metadata'), ('watermark', 'Watermark')], max_length=30)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output_file', models.ImageField(blank=True, max_length=500, upload_to=images.models.result_upload_path)),
                ('output_size', models.PositiveBigIntegerField(default=0)),
                ('output_width', models.PositiveIntegerField(blank=True, null=True)),
                ('output_height', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_operations', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='images.uploadedimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_bytes', models.PositiveBigIntegerField(default=0)),
                ('limit_bytes', models.PositiveBigIntegerField(default=262144000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('used_bytes__lte', models.F('limit_bytes'))), name='quota_used_lte_limit')],
            },
        ),
        migrations.CreateModel(
            name='TemporaryDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('max_downloads', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('download_count', models.PositiveSmallIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='images.imageoperation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token', 'expires_at'], name='download_token_exp_idx'), models.Index(fields=['owner', '-created_at'], name='download_owner_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['owner', '-created_at'], name='img_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['owner', '-updated_at'], name='img_owner_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['status', 'created_at'], name='img_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['expires_at'], name='img_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='imageoperation',
            index=models.Index(fields=['owner', '-created_at'], name='op_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='imageoperation',
            index=models.Index(fields=['image', 'status'], name='op_image_status_idx'),
        ),
        migrations.AddIndex(
            model_name='imageoperation',
            index=models.Index(fields=['status', 'created_at'], name='op_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='imageoperation',
            constraint=models.UniqueConstraint(fields=('id', 'owner'), name='op_id_owner_unique'),
        ),
    ]
