# Generated by Django 6.0.7 on 2026-07-13 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imageoperation',
            name='op_id_owner_unique',
        ),
        migrations.RemoveIndex(
            model_name='temporarydownload',
            name='download_token_exp_idx',
        ),
        migrations.AddIndex(
            model_name='temporarydownload',
            index=models.Index(fields=['expires_at'], name='download_expires_idx'),
        ),
    ]
